---
title: "Data Mining Chapter 9 HW"
author: "Pooria Assarehha"
date: "2024-01-24"
output: pdf_document
---

# Discovering Knowledge in Data Chapter 9 Exercises

## Ex 9.1

## Ex 9.10

Large Values may cause gradient decent to never converge, and always shoot over the minimum.

small values may take a lot of time and waste energy. 

# Hands-on Analysis

## Ex 9.12

```{r}
setwd("~/Documents/Amar 1400 UT/4021_Fall 2023/Data Mining/Assignment")
churn = read.csv('../churn.csv', stringsAsFactors = TRUE)

str(churn)
```

Phone Field is uninformative. 2 level factors must be mapped to 0 and 1. 

```{r}
churn = churn[-4]
summary(churn)
```
Voice mail Plan and Voice mail msgs have inter effect.

```{r}
for(col in 2:length(churn)){
  if(is.numeric(churn[,col]))
    churn[,col] <- (churn[,col] - mean(churn[,col]))/sd(churn[,col])
  else {levels(churn[,col]) <- c(0,1); churn[,col] <- as.integer(churn[,col])}
}
str(churn)
```

```{r, message=FALSE}
library(caret)
dmyvars <- as.data.frame(model.matrix(~0+churn$State , churn[,1]))
colnames(dmyvars) <- gsub("churn\\$", "", colnames(dmyvars))
df = cbind(dmyvars,churn[-1])
str(df)
```

```{r}
library(neuralnet)
net <- neuralnet(Churn. ~ ., data = df, hidden = 10, rep = 1 )
```

```{r, fig.height=100}
plot(net, show.weights = FALSE)
```

## Ex 9.13
