---
title: "Data Mining Classwork 9"
author: "Pooria Assarehha"
date: "2024-01-13"
output: pdf_document
---

```{r}
x = matrix(c(0.4, 0.2, 0.7), ncol = 3)
y = 0.8
x
```

```{r}
W1 = matrix(
  c(0.5, 0.6, 0.8, 0.6, 0.7, 0.9, 0.8, 0.4),
  ncol = 2, byrow=FALSE
  )
colnames(W1) <- c("A", "B")
rownames(W1) <- c("W0", "W1", "W2", "W3")
W1
```

```{r}
W2 = matrix(
  c(0.5, 0.9, 0.9),
  ncol = 1
  )
colnames(W2) <- c("Z")
rownames(W2) <- c("W0Z", "WAZ", "WBZ")
W2
```

```{r}
net1 = cbind(1, x) %*% W1 
O1 = 1 / (1 +  exp(-net1))
net2 = cbind(1, O1) %*% W2 
O2 = 1 / (1 +  exp(-net2))
O1
O2
```

```{r}
deltaZ = O2*(1-O2)*(y-O2)
deltaZ

deltaAB = O1*(1-O1)
deltaA = deltaAB[1,1]*W2[2,1]*deltaZ
deltaB = deltaAB[1,2]*W2[3,1]*deltaZ

deltaA
deltaB

```

```{r}
eta = 0.1

dW2 = eta* rbind(1, t(O1))  %*% deltaZ
dW2

dW1 = eta* t(cbind(1, x)) %*% cbind(deltaA, deltaB)
colnames(dW1) <- c("A", "B")
dW1
```

these are the updated weights for node B:

```{r}
W1 = W1 + dW1
W2 = W2 + dW2
W1[,2]
```

```{r}
updated_net1 = cbind(1, x) %*% W1 
updated_O1 = 1 / (1 +  exp(-updated_net1))
updated_net2 = cbind(1, updated_O1) %*% W2 
updated_O2 = 1 / (1 +  exp(-updated_net2))
new_Loss = (updated_O2 - 0.8)^2
Loss = (O2 - 0.8)^2
Loss
new_Loss
```

Loss has Slightly decreased. after one iteration of Gradient Decent.
